const spells = [
    {
      name: "Acid Arrow",
      casting_time: "1 action",
      casting_time_misc: "",
      component_material: "powdered rhubarb leaf and an adder's stomach",
      component_semantic: true,
      component_verbal: true,
      component_misc: "",
      description: "A shimmering green arrow streaks toward a target within range and bursts in a spray of acid. Make a ranged spell attack against the target. On a hit, the target takes 4d4 acid damage immediately and 2d4 acid damage at the end of its next turn. On a miss, the arrow splashes the target with acid for half as much of the initial damage and no damage at the end of its next turn. ***At Higher Levels***. When you cast this spell using a spell slot of 3rd level or higher, the damage (both initial and later) increases by 1d4 for each slot level above 2nd.",
      duration: "Instantaneous",
      level: "2nd-level",
      range: "90 feet",
      range_area: "",
      school: "evocation",
      school_ritual: ""
    },
    {
      name: "Acid Splash",
      casting_time: "1 action",
      casting_time_misc: "",
      component_material: "",
      component_semantic: true,
      component_verbal: true,
      component_misc: "",
      description: "You hurl a bubble of acid. Choose one creature you can see within range, or choose two creatures you can see within range that are within 5 feet of each other. A target must succeed on a Dexterity saving throw or take 1d6 acid damage. This spell's damage increases by 1d6 when you reach 5th level (2d6), 11th level (3d6), and 17th level (4d6).",
      duration: "Instantaneous",
      level: "cantrip",
      range: "60 feet",
      range_area: "",
      school: "conjuration",
      school_ritual: ""
    },
    {
      name: "Aid",
      casting_time: "1 action",
      casting_time_misc: "",
      component_material: "a tiny strip of white cloth",
      component_semantic: true,
      component_verbal: true,
      component_misc: "",
      description: "Your spell bolsters your allies with toughness and resolve. Choose up to three creatures within range. Each target's hit point maximum and current hit points increase by 5 for the duration. ***At Higher Levels***. When you cast this spell using a spell slot of 3rd level or higher, a target's hit points increase by an additional 5 for each slot level above 2nd.",
      duration: "8 hours",
      level: "2nd-level",
      range: "30 feet",
      range_area: "",
      school: "abjuration",
      school_ritual: ""
    },
    {
      name: "Alarm",
      casting_time: "1 minute",
      casting_time_misc: "",
      component_material: "a tiny bell and a piece of fine silver wire",
      component_semantic: true,
      component_verbal: true,
      component_misc: "",
      description: "You set an alarm against unwanted intrusion. Choose a door, a window, or an area within range that is no larger than a 20-foot cube. Until the spell ends, an alarm alerts you whenever a Tiny or larger creature touches or enters the warded area. When you cast the spell, you can designate creatures that won't set off the alarm. You also choose whether the alarm is mental or audible. A mental alarm alerts you with a ping in your mind if you are within 1 mile of the warded area. This ping awakens you if you are sleeping. An audible alarm produces the sound of a hand bell for 10 seconds within 60 feet.",
      duration: "8 hours",
      level: "1st-level",
      range: "30 feet",
      range_area: "",
      school: "abjuration",
      school_ritual: "(ritual)"
    },
    {
      name: "Alter Self",
      casting_time: "1 action",
      casting_time_misc: "",
      component_material: "",
      component_semantic: true,
      component_verbal: true,
      component_misc: "",
      description: "You assume a different form. When you cast the spell, choose one of the following options, the effects of which last for the duration of the spell. While the spell lasts, you can end one option as an action to gain the benefits of a different one. ***Aquatic Adaptation***. You adapt your body to an aquatic environment, sprouting gills and growing webbing between your fingers. You can breathe underwater and gain a swimming speed equal to your walking speed. ***Change Appearance***. You transform your appearance. You decide what you look like, including your height, weight, facial features, sound of your voice, hair length, coloration, and distinguishing characteristics, if any. You can make yourself appear as a member of another race, though none of your statistics change. You also can't appear as a creature of a different size than you, and your basic shape stays the same; if you're bipedal, you can't use this spell to become quadrupedal, for instance. At any time for the duration of the spell, you can use your action to change your appearance in this way again. ***Natural Weapons***. You grow claws, fangs, spines, horns, or a different natural weapon of your choice. Your unarmed strikes deal 1d6 bludgeoning, piercing, or slashing damage, as appropriate to the natural weapon you chose, and you are proficient with your unarmed strikes. Finally, the natural weapon is magic and you have a +1 bonus to the attack and damage rolls you make using it.",
      duration: "Concentration, up to 1 hour",
      level: "2nd-level",
      range: "Self",
      range_area: "",
      school: "transmutation",
      school_ritual: ""
    },
    {
      name: "Animal Friendship",
      casting_time: "1 action",
      casting_time_misc: "",
      component_material: "a morsel of food",
      component_semantic: true,
      component_verbal: true,
      component_misc: "",
      description: "This spell lets you convince a beast that you mean it no harm. Choose a beast that you can see within range. It must see and hear you. If the beast's Intelligence is 4 or higher, the spell fails. Otherwise, the beast must succeed on a Wisdom saving throw or be charmed by you for the spell's duration. If you or one of your companions harms the target, the spells ends. ***At Higher Levels***. When you cast this spell using a spell slot of 2nd level or higher, you can affect one additional beast t level above 1st.",
      duration: "24 hours",
      level: "1st-level",
      range: "30 feet",
      range_area: "",
      school: "enchantment",
      school_ritual: ""
    },
    {
        name: "Animal Messenger",
        casting_time: "1 action",
        casting_time_misc: "",
        component_material: "a morsel of food",
        component_semantic: true,
        component_verbal: true,
        component_misc: "",
        description: "By means of this spell, you use an animal to deliver a message. Choose a Tiny beast you can see within range, such as a squirrel, a blue jay, or a bat. You specify a location, which you must have visited, and a recipient who matches a general description, such as \"a man or woman dressed in the uniform of the town guard\" or \"a red-haired dwarf wearing a pointed hat.\" You also speak a message of up to twenty-five words. The target beast travels for the duration of the spell toward the specified location, covering about 50 miles per 24 hours for a flying messenger, or 25 miles for other animals. When the messenger arrives, it delivers your message to the creature that you described, replicating the sound of your voice. The messenger speaks only to a creature matching the description you gave. If the messenger doesn't reach its destination before the spell ends, the message is lost, and the beast makes its way back to where you cast this spell. ***At Higher Levels***. If you cast this spell using a spell slot of 3nd level or higher, the duration of the spell increases by 48 hours for each slot level above 2nd.",
        duration: "24 hours",
        level: "2nd-level",
        range: "30 feet",
        range_area: "",
        school: "enchantment",
        school_ritual: "(ritual)"
      },
      {
        name: "Animal Shapes",
        casting_time: "1 action",
        casting_time_misc: "",
        component_material: "",
        component_semantic: true,
        component_verbal: true,
        component_misc: "",
        description: "Your magic turns others into beasts. Choose any number of willing creatures that you can see within range. You transform each target into the form of a Large or smaller beast with a challenge rating of 4 or lower. On subsequent turns, you can use your action to transform affected creatures into new forms. The transformation lasts for the duration for each target, or until the target drops to 0 hit points or dies. You can choose a different form for each target. A target's game statistics are replaced by the statistics of the chosen beast, though the target retains its alignment and Intelligence, Wisdom, and Charisma scores. The target assumes the hit points of its new form, and when it reverts to its normal form, it returns to the number of hit points it had before it transformed. If it reverts as a result of dropping to 0 hit points, any excess damage carries over to its normal form. As long as the excess damage doesn't reduce the creature's normal form to 0 hit points, it isn't knocked unconscious. The creature is limited in the actions it can perform by the nature of its new form, and it can't speak or cast spells. The target's gear melds into the new form. The target can't activate, wield, or otherwise benefit from any of its equipment.",
        duration: "Concentration, up to 24 hours",
        level: "8th-level",
        range: "30 feet",
        range_area: "",
        school: "transmutation",
        school_ritual: ""
      },
      {
        name: "Animate Dead",
        casting_time: "1 minute",
        casting_time_misc: "",
        component_material: "a drop of blood, a piece of flesh, and a pinch of bone dust",
        component_semantic: true,
        component_verbal: true,
        component_misc: "",
        description: "This spell creates an undead servant. Choose a pile of bones or a corpse of a Medium or Small humanoid within range. Your spell imbues the target with a foul mimicry of life, raising it as an undead creature. The target becomes a skeleton if you chose bones or a zombie if you chose a corpse (the GM has the creature's game statistics). On each of your turns, you can use a bonus action to mentally command any creature you made with this spell if the creature is within 60 feet of you (if you control multiple creatures, you can command any or all of them at the same time, issuing the same command to each one). You decide what action the creature will take and where it will move during its next turn, or you can issue a general command, such as to guard a particular chamber or corridor. If you issue no commands, the creature only defends itself against hostile creatures. Once given an order, the creature continues to follow it until its task is complete. The creature is under your control for 24 hours, after which it stops obeying any command you've given it. To maintain control of the creature for another 24 hours, you must cast this spell on the creature again before the current 24-hour period ends. This use of the spell reasserts your control over up to four creatures you have animated with this spell, rather than animating a new one. ***At Higher Levels***. When you cast this spell using a spell slot of 4th level or higher, you animate or reassert control over two additional undead creatures for each slot level above 3rd. Each of the creatures must come from a different corpse or pile of bones.",
        duration: "Instantaneous",
        level: "3rd-level",
        range: "10 feet",
        range_area: "",
        school: "necromancy",
        school_ritual: ""
      },
      {
        name: "Animate Objects",
        casting_time: "1 action",
        casting_time_misc: "",
        component_material: "",
        component_semantic: true,
        component_verbal: true,
        component_misc: "",
        description: "Objects come to life at your command. Choose up to ten nonmagical objects within range that are not being worn or carried. Medium targets count as two objects, Large targets count as four objects, Huge targets count as eight objects. You can't animate any object larger than Huge. Each target animates and becomes a creature under your control until the spell ends or until reduced to 0 hit points. As a bonus action, you can mentally command any creature you made with this spell if the creature is within 500 feet of you (if you control multiple creatures, you can command any or all of them at the same time, issuing the same command to each one). You decide what action the creature will take and where it will move during its next turn, or you can issue a general command, such as to guard a particular chamber or corridor. If you issue no commands, the creature only defends itself against hostile creatures. Once given an order, the creature continues to follow it until its task is complete. An animated object is a construct with AC, hit points, attacks, Strength, and Dexterity determined by its size. Its Constitution is 10 and its Intelligence and Wisdom are 3, and its Charisma is 1. Its speed is 30 feet; if the object lacks legs or other appendages it can use for locomotion, it instead has a flying speed of 30 feet and can hover. If the object is securely attached to a surface or a larger object, such as a chain bolted to a wall, its speed is 0. It has blindsight with a radius of 30 feet and is blind beyond that distance. When the animated object drops to 0 hit points, it reverts to its original object form, and any remaining damage carries over to its original object form. If you command an object to attack, it can make a single melee attack against a creature within 5 feet of it. It makes a slam attack with an attack bonus and bludgeoning damage determined by its size. The GM might rule that a specific object inflicts slashing or piercing damage based on its form. ***At Higher Levels***. If you cast this spell using a spell slot of 6th level or higher, you can animate two additional objects for each slot level above 5th.",
        duration: "Concentration, up to 1 minute",
        level: "5th-level",
        range: "120 feet",
        range_area: "",
        school: "transmutation",
        school_ritual: ""
      },
      {
        name: "Antilife Shell",
        casting_time: "1 action",
        casting_time_misc: "",
        component_material: "",
        component_semantic: "S",
        component_verbal: "V",
        component_misc: "",
        description: "A shimmering barrier extends out from you in a 10-foot radius and moves with you, remaining centered on you and hedging out creatures other than undead and constructs. The barrier lasts for the duration of the spell.\nThe barrier prevents an affected creature from passing through or entering, as well as any spell, object, or other effect. An affected creature can use its action to make a Wisdom saving throw against your spell save DC. On a successful save, the creature can pass through the barrier and remains protected for 1 minute.\n***At Higher Levels***. If you cast this spell using a spell slot of 5th level or higher, the radius of the barrier increases by 5 feet for each slot level above 4th.",
        duration: "Concentration, up to 1 hour",
        level: "4th-level",
        range: "Self",
        range_area: "",
        school: "abjuration",
        school_ritual: ""
      },
      {
      name: "Dancing Lights",
      casting_time: "1 action",
      casting_time_misc: "",
      component_material: "Misc",
      component_semantic: "S",
      component_verbal: "V",
      component_misc: "a bit of phosphorus or wychwood, or a glowworm",
      description: "You create up to four torch-sized lights within range, making them appear as torches, lanterns, or glowing orbs that hover in the air for the duration. You can also combine the four lights into one glowing vaguely humanoid form of Medium size. Whichever form you choose, each light sheds dim light in a 10-foot radius.\nAs a bonus action on your turn, you can move the lights up to 60 feet to a new spot within range. A light must be within 20 feet of another light created by this spell, and a light winks out if it exceeds the spell's range.",
      duration: "Concentration, up to 1 minute",
      level: "cantrip",
      range: "120 feet",
      range_area: "",
      school: "evocation",
      school_ritual: ""
    },
    {
      name: "Darkness",
      casting_time: "1 action",
      casting_time_misc: "",
      component_material: "Misc",
      component_semantic: "",
      component_verbal: "V",
      component_misc: "bat fur and a drop of pitch or piece of coal",
      description: "Magical darkness spreads from a point you choose within range to fill a 15-foot radius sphere for the duration. The darkness spreads around corners. A creature with darkvision can't see through this darkness, and nonmagical light can't illuminate it.\nIf the point you choose is on an object you are holding or one that isn't being worn or carried, the darkness emanates from the object and moves with it. Completely covering the source of the darkness with an opaque object, such as a bowl or a helm, blocks the darkness.\n\nIf any of this spell's area overlaps with an area of light created by a spell of 2nd level or lower, the spell that created the light is dispelled.",
      duration: "Concentration, up to 10 minutes",
      level: "2nd-level",
      range: "60 feet",
      range_area: "",
      school: "evocation",
      school_ritual: ""
    },
    {
      name: "Darkvision",
      casting_time: "1 action",
      casting_time_misc: "",
      component_material: "Misc",
      component_semantic: "S",
      component_verbal: "V",
      component_misc: "either a pinch of dried carrot or an agate",
      description: "You touch a willing creature to grant it the ability to see in the dark. For the duration, that creature has darkvision out to a range of 60 feet.",
      duration: "8 hours",
      level: "2nd-level",
      range: "Touch",
      range_area: "",
      school: "transmutation",
      school_ritual: ""
    },
    {
      name: "Daylight",
      casting_time: "1 action",
      casting_time_misc: "",
      component_material: "",
      component_semantic: "S",
      component_verbal: "V",
      component_misc: "",
      description: "A 60-foot radius sphere of light spreads out from a point you choose within range. The sphere is bright light and sheds dim light for an additional 60 feet.\nIf you chose a point on an object you are holding or one that isn't being worn or carried, the light shines from the object and moves with it. Completely covering the affected object with an opaque object, such as a bowl or a helm, blocks the light.\n\nIf any of this spell's area overlaps with an area of darkness created by a spell of 3rd level or lower, the spell that created the darkness is dispelled.",
      duration: "1 hour",
      level: "3rd-level",
      range: "60 feet",
      range_area: "",
      school: "evocation",
      school_ritual: ""
    },
    {
      name: "Death Ward",
      casting_time: "1 action",
      casting_time_misc: "",
      component_material: "",
      component_semantic: "S",
      component_verbal: "V",
      component_misc: "",
      description: "You touch a creature and grant it a measure of protection from death.\nThe first time the target would drop to 0 hit points as a result of taking damage, the target instead drops to 1 hit point, and the spell ends.\n\nIf the spell is still in effect when the target is subjected to an effect that would kill it instantaneously without dealing damage, that effect is instead negated against the target, and the spell ends.",
      duration: "8 hours",
      level: "4th-level",
      range: "Touch",
      range_area: "",
      school: "abjuration",
      school_ritual: ""
    },
    {
      name: "Delayed Blast Fireball",
      casting_time: "1 action",
      casting_time_misc: "",
      component_material: "Misc",
      component_semantic: "S",
      component_verbal: "V",
      component_misc: "a tiny ball of bat guano and sulfur",
      description: "A beam of yellow light flashes from your pointing finger, then condenses to linger at a chosen point within range as a glowing bead for the duration. When the spell ends, either because your concentration is broken or because you decide to end it, the bead blossoms with a low roar into an explosion of flame that spreads around corners. Each creature in a 20-foot radius sphere centered on that point must make a Dexterity saving throw. A creature takes fire damage equal to the total accumulated damage on a failed save, or half as much damage on a successful one.\n\nThe spell's base damage is 12d6. If at the end of your turn the bead has not yet detonated, the damage increases by 1d6.\n\nIf the glowing bead is touched before the interval has expired, the creature touching it must make a Dexterity saving throw. On a failed save, the spell ends immediately, causing the bead to erupt in flame. On a successful save, the creature can throw the bead up to 40 feet. When it strikes a creature or a solid object, the spell ends, and the bead explodes.\n\nThe fire damages objects in the area and ignites flammable objects that aren't being worn or carried.\n\n***At Higher Levels***. When you cast this spell using a spell slot of 8th level or higher, the base damage increases by 1d6 for each slot level above 7th.",
      duration: "Concentration, up to 1 minute",
      level: "7th-level",
      range: "150 feet",
      range_area: "",
      school: "evocation",
      school_ritual: ""
    },
    {
      name: "Demiplane",
      casting_time: "1 action",
      casting_time_misc: "",
      component_material: "",
      component_semantic: "S",
      component_verbal: "",
      component_misc: "",
      description: "You create a shadowy door on a flat solid surface that you can see within range. The door is large enough to allow Medium creatures to pass through unhindered. When opened, the door leads to a demiplane that appears to be an empty room 30 feet in each dimension, made of wood or stone. When the spell ends, the door disappears, and any creatures or objects inside the demiplane remain trapped there, as the door also disappears from the other side.\nEach time you cast this spell, you can create a new demiplane, or have the shadowy door connect to a demiplane you created with a previous casting of this spell. Additionally, if you know the nature and contents of a demiplane created by a casting of this spell by another creature, you can have the shadowy door connect to its demiplane instead.",
      duration: "1 hour",
      level: "8th-level",
      range: "60 feet",
      range_area: "",
      school: "conjuration",
      school_ritual: ""
    },
    {
      name: "Detect Evil and Good",
      casting_time: "1 action",
      casting_time_misc: "",
      component_material: "",
      component_semantic: "S",
      component_verbal: "V",
      component_misc: "",
      description: "For the duration, you know if there is an aberration, celestial, elemental, fey, fiend, or undead within 30 feet of you, as well as where the creature is located. Similarly, you know if there is a place or object within 30 feet of you that has been magically consecrated or desecrated.\nThe spell can penetrate most barriers, but it is blocked by 1 foot of stone, 1 inch of common metal, a thin sheet of lead, or 3 feet of wood or dirt.",
      duration: "Concentration, up to 10 minutes",
      level: "1st-level",
      range: "Self",
      range_area: "",
      school: "divination",
      school_ritual: ""
    },
    {
      name: "Detect Magic",
      casting_time: "1 action",
      casting_time_misc: "",
      component_material: "",
      component_semantic: "S",
      component_verbal: "V",
      component_misc: "",
      description: "For the duration, you sense the presence of magic within 30 feet of you. If you sense magic in this way, you can use your action to see a faint aura around any visible creature or object in the area that bears magic, and you learn its school of magic, if any.\nThe spell can penetrate most barriers, but it is blocked by 1 foot of stone, 1 inch of common metal, a thin sheet of lead, or 3 feet of wood or dirt.",
      duration: "Concentration, up to 10 minutes",
      level: "1st-level",
      range: "Self",
      range_area: "",
      school: "divination",
      school_ritual: "(ritual)"
    },
    {
      name: "Detect Poison and Disease",
      casting_time: "1 action",
      casting_time_misc: "",
      component_material: "Misc",
      component_semantic: "S",
      component_verbal: "V",
      component_misc: "a yew leaf",
      description: "For the duration, you can sense the presence and location of poisons, poisonous creatures, and diseases within 30 feet of you. You also identify the kind of poison, poisonous creature, or disease in each case.\nThe spell can penetrate most barriers, but it is blocked by 1 foot of stone, 1 inch of common metal, a thin sheet of lead, or 3 feet of wood or dirt.",
      duration: "Concentration, up to 10 minutes",
      level: "1st-level",
      range: "Self",
      range_area: "",
      school: "divination",
      school_ritual: "(ritual)"
    },
    {
      name: "Detect Thoughts",
      casting_time: "1 action",
      casting_time_misc: "",
      component_material: "Misc",
      component_semantic: "S",
      component_verbal: "V",
      component_misc: "a copper piece",
      description: "For the duration, you can read the thoughts of certain creatures. When you cast the spell and as your action on each turn until the spell ends, you can focus your mind on any one creature that you can see within 30 feet of you. If the creature you choose has an Intelligence of 3 or lower or doesn't speak any language, the creature is unaffected.\nYou initially learn the surface thoughts of the creature-what is most on its mind in that moment. As an action, you can either shift your attention to another creature's thoughts or attempt to probe deeper into the same creature's mind. If you probe deeper, the target must make a Wisdom saving throw. If it fails, you gain insight into its reasoning (if any), its emotional state, and something that looms large in its mind (such as something it worries over, loves, or hates). If it succeeds, the spell ends. Either way, the target knows that you are probing into its mind, and unless you shift your attention to another creature's thoughts, the creature can use its action on its turn to make an Intelligence check contested by your Intelligence check; if it succeeds, the spell ends.\nQuestions verbally directed at the target creature naturally shape the course of its thoughts, so this spell is particularly effective as part of an interrogation.\n\nYou can also use this spell to detect the presence of thinking creatures you can't see. When you cast the spell or as your action during the duration, you can search for thoughts within 30 feet of you. The spell can penetrate barriers, but 2 feet of rock, 2 inches of any metal other than lead, or a thin sheet of lead blocks you. You can't detect a creature with an Intelligence of 3 or lower or one that doesn't speak any language.\nOnce you detect the presence of a creature in this way, you can read its thoughts for the rest of the duration as described above, even if you can't see it, but it must still be within range.",
      duration: "Concentration, up to 1 minute",
      level: "2nd-level",
      range: "Self",
      range_area: "",
      school: "divination",
      school_ritual: ""
    },
    {
      name: "Dimension Door",
      casting_time: "1 action",
      casting_time_misc: "",
      component_material: "",
      component_semantic: "",
      component_verbal: "V",
      component_misc: "",
      description: "You teleport yourself from your current location to any other spot within range. You arrive at exactly the spot desired. It can be a place you can see, one you can visualize, or one you can describe by stating distance and direction, such as \"200 feet straight downward\" or \"upward to the northwest at a 45-degree angle, 300 feet.\"\nYou can bring along objects as long as their weight doesn't exceed what you can carry. You can also bring one willing creature of your size or smaller who is carrying gear up to its carrying capacity. The creature must be within 5 feet of you when you cast this spell.\n\nIf you would arrive in a place already occupied by an object or a creature, you and any creature traveling with you each take 4d6 force damage, and the spell fails to teleport you.",
      duration: "Instantaneous",
      level: "4th-level",
      range: "500 feet",
      range_area: "",
      school: "conjuration",
      school_ritual: ""
    }
  ];

  export default spells